name: build-and-push-container-image
on:
  release:
    types:
      - published

jobs:
  build-and-push-container-image:
    name: Build and push container image
    runs-on: ubuntu-latest
    steps:
      - name: Determine last tag version
        id: next_version
        run: |
          maybe_tag=$(git tag | sort -V | tail -1)
          tag=${maybe_tag:-v0.0.0}
          version=${tag:1}
          echo "Current version is $version"

          echo "version=$version" >> $GITHUB_OUTPUT

      - name: Checkout GIT repository
        uses: actions/checkout@v3A
        with:
          ref: v${{ steps.next_version.outputs.version }}

      - name: Replace VERSION inside python script
        run: |
          SCRIPT='./src/app/dsb2pushover.py'
          grep "^VERSION=" ${SCRIPT}
          sed -i -e "s/^VERSION=.*$/VERSION='${{ steps.next_version.outputs.version }}'/" ${SCRIPT}
          grep "^VERSION=" ${SCRIPT}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to container registry
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          context: .
          platforms: linux/amd64, linux/arm64
          tags: oitc/dsb2pushover:${{ steps.next_version.outputs.version }},oitc/dsb2pushover:latest
          labels: |
            site.local.program.version=${{ steps.next_version.outputs.version }}
            context.github.repositoryUrl=${{ github.repositoryUrl }}
            context.github.actor=${{ github.actor }}
            context.github.event.repository.updated_at=${{ github.event.repository.updated_at}}
            context.github.ref=${{ github.ref }}
            context.github.job=${{ github.job }}
            context.runner.os=${{ runner.os }}
            context.runner.arch=${{ runner.arch }}
